// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package database

import (
	"context"
	"fmt"
	"io"
	"sync/atomic"

	"github.com/go-sql-driver/mysql"
	"github.com/hexon/mysqltsv"
)

var readerHandlerSequenceForCreateEmptyTestCaseResults uint32 = 1

func convertRowsForCreateEmptyTestCaseResults(w *io.PipeWriter, arg []CreateEmptyTestCaseResultsParams) {
	e := mysqltsv.NewEncoder(w, 6, nil)
	for _, row := range arg {
		e.AppendValue(row.ID)
		e.AppendString(row.Status)
		e.AppendString(row.Time)
		e.AppendValue(row.Memory)
		e.AppendString(row.TestCaseID)
		e.AppendString(row.SubmissionID)
	}
	w.CloseWithError(e.Close())
}

// CreateEmptyTestCaseResults uses MySQL's LOAD DATA LOCAL INFILE and is not atomic.
//
// Errors and duplicate keys are treated as warnings and insertion will
// continue, even without an error for some cases.  Use this in a transaction
// and use SHOW WARNINGS to check for any problems and roll back if you want to.
//
// Check the documentation for more information:
// https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-error-handling
func (q *Queries) CreateEmptyTestCaseResults(ctx context.Context, arg []CreateEmptyTestCaseResultsParams) (int64, error) {
	pr, pw := io.Pipe()
	defer pr.Close()
	rh := fmt.Sprintf("CreateEmptyTestCaseResults_%d", atomic.AddUint32(&readerHandlerSequenceForCreateEmptyTestCaseResults, 1))
	mysql.RegisterReaderHandler(rh, func() io.Reader { return pr })
	defer mysql.DeregisterReaderHandler(rh)
	go convertRowsForCreateEmptyTestCaseResults(pw, arg)
	// The string interpolation is necessary because LOAD DATA INFILE requires
	// the file name to be given as a literal string.
	result, err := q.db.ExecContext(ctx, fmt.Sprintf("LOAD DATA LOCAL INFILE '%s' INTO TABLE `test_case_result` %s (id, status, time, memory, test_case_id, submission_id)", "Reader::"+rh, mysqltsv.Escaping))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
