// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Company struct {
	ID          string
	Name        string
	Description string
	Website     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ImageUrl    string
	UserID      string
}

type Education struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Institution string
	Degree      string
	StartDate   time.Time
	EndDate     sql.NullTime
	UserID      string
}

type Example struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Input     string
	Output    string
	ProblemID string
}

type Experience struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Company   string
	Title     string
	StartDate time.Time
	EndDate   sql.NullTime
	UserID    string
}

type Jwt struct {
	RefreshToken string
	CreatedAt    time.Time
}

type Language struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	DisplayName string
}

type LanguageQuiz struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LanguageID int32
	QuizID     string
}

type Link struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Url       string
	Name      string
	UserID    string
}

type Offer struct {
	ID           string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Title        string
	About        string
	Requirements string
	Benefits     string
	Status       int32
	MinWage      int32
	MaxWage      int32
	CompanyID    string
}

type Participation struct {
	ID        string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ExpiresAt time.Time
	UserID    string
	QuizID    string
}

type Problem struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description string
	Title       string
	MemoryLimit int32
	TimeLimit   int32
	QuizID      string
}

type Quiz struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Duration  int32
	OfferID   string
}

type Skill struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UserID    string
}

type StrokeWindow struct {
	ID              string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	StrokeAmount    int32
	UdMean          int32
	UdStdDev        int32
	Du1Mean         int32
	Du1StdDev       int32
	Du2Mean         int32
	Du2StdDev       int32
	DdMean          int32
	DdStdDev        int32
	UuMean          int32
	UuStdDev        int32
	ParticipationID string
}

type Submission struct {
	ID                string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	Src               string
	AcceptedTestCases uint8
	ProblemID         string
	ParticipationID   string
	LanguageID        int32
}

type TestCase struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Input     string
	Output    string
	ProblemID string
}

type TestCaseResult struct {
	ID           sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Output       string
	Status       string
	Time         int32
	Memory       int32
	TestCaseID   string
	SubmissionID string
}

type User struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Nick        string
	Password    string
	Name        string
	Email       string
	Description string
	ImageUrl    string
	Number      string
}
