// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: participation.sql

package database

import (
	"context"
	"time"
)

const participate = `-- name: Participate :exec
INSERT INTO participation (id, user_id, quiz_id)
VALUES (?, ?, ?)
`

type ParticipateParams struct {
	ID     string
	UserID string
	QuizID string
}

func (q *Queries) Participate(ctx context.Context, arg ParticipateParams) error {
	_, err := q.db.ExecContext(ctx, participate, arg.ID, arg.UserID, arg.QuizID)
	return err
}

const participationStatus = `-- name: ParticipationStatus :one
SELECT participation.id, participation.expires_at
FROM participation
WHERE participation.user_id = ? AND participation.quiz_id = ?
`

type ParticipationStatusParams struct {
	UserID string
	QuizID string
}

type ParticipationStatusRow struct {
	ID        string
	ExpiresAt time.Time
}

func (q *Queries) ParticipationStatus(ctx context.Context, arg ParticipationStatusParams) (ParticipationStatusRow, error) {
	row := q.db.QueryRowContext(ctx, participationStatus, arg.UserID, arg.QuizID)
	var i ParticipationStatusRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}
