// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: quizzes.sql

package database

import (
	"context"
	"time"
)

const getQuiz = `-- name: GetQuiz :one
SELECT quiz.id, quiz.created_at, quiz.updated_at, quiz.title, quiz.description, quiz.duration, quiz.user_id, user.name as author
FROM quiz
JOIN user ON quiz.user_id = user.id
WHERE quiz.id = ?
`

type GetQuizRow struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
	Duration    int32
	UserID      string
	Author      string
}

func (q *Queries) GetQuiz(ctx context.Context, id string) (GetQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, id)
	var i GetQuizRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.Duration,
		&i.UserID,
		&i.Author,
	)
	return i, err
}

const getQuizzes = `-- name: GetQuizzes :many
SELECT quiz.id, quiz.title, user.name as author
FROM quiz
JOIN user ON quiz.user_id = user.id
ORDER BY quiz.created_at DESC
LIMIT 10
`

type GetQuizzesRow struct {
	ID     string
	Title  string
	Author string
}

func (q *Queries) GetQuizzes(ctx context.Context) ([]GetQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuizzesRow
	for rows.Next() {
		var i GetQuizzesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Author); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
