// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stroke_window.sql

package database

import (
	"context"
)

const insertStrokeWindow = `-- name: InsertStrokeWindow :exec
INSERT INTO stroke_window
(id, participation_id, stroke_amount, 
ud_mean, ud_std_dev, 
du1_mean, du1_std_dev, 
du2_mean, du2_std_dev, 
dd_mean, dd_std_dev, 
uu_mean, uu_std_dev)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStrokeWindowParams struct {
	ID              string
	ParticipationID string
	StrokeAmount    int32
	UdMean          int32
	UdStdDev        int32
	Du1Mean         int32
	Du1StdDev       int32
	Du2Mean         int32
	Du2StdDev       int32
	DdMean          int32
	DdStdDev        int32
	UuMean          int32
	UuStdDev        int32
}

func (q *Queries) InsertStrokeWindow(ctx context.Context, arg InsertStrokeWindowParams) error {
	_, err := q.db.ExecContext(ctx, insertStrokeWindow,
		arg.ID,
		arg.ParticipationID,
		arg.StrokeAmount,
		arg.UdMean,
		arg.UdStdDev,
		arg.Du1Mean,
		arg.Du1StdDev,
		arg.Du2Mean,
		arg.Du2StdDev,
		arg.DdMean,
		arg.DdStdDev,
		arg.UuMean,
		arg.UuStdDev,
	)
	return err
}

const selectStrokeWindows = `-- name: SelectStrokeWindows :many
SELECT stroke_window.id, stroke_window.created_at, stroke_window.updated_at, stroke_window.stroke_amount, stroke_window.ud_mean, stroke_window.ud_std_dev, stroke_window.du1_mean, stroke_window.du1_std_dev, stroke_window.du2_mean, stroke_window.du2_std_dev, stroke_window.dd_mean, stroke_window.dd_std_dev, stroke_window.uu_mean, stroke_window.uu_std_dev, stroke_window.participation_id
FROM stroke_window
WHERE participation_id = ?
ORDER BY created_at DESC
`

func (q *Queries) SelectStrokeWindows(ctx context.Context, participationID string) ([]StrokeWindow, error) {
	rows, err := q.db.QueryContext(ctx, selectStrokeWindows, participationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StrokeWindow
	for rows.Next() {
		var i StrokeWindow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StrokeAmount,
			&i.UdMean,
			&i.UdStdDev,
			&i.Du1Mean,
			&i.Du1StdDev,
			&i.Du2Mean,
			&i.Du2StdDev,
			&i.DdMean,
			&i.DdStdDev,
			&i.UuMean,
			&i.UuStdDev,
			&i.ParticipationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
