// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: submissions.sql

package database

import (
	"context"
	"time"
)

const createSubmission = `-- name: CreateSubmission :exec
INSERT INTO submission 
(id, src, time, problem_id, user_id, language_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSubmissionParams struct {
	ID         string
	Src        string
	Time       time.Time
	ProblemID  string
	UserID     string
	LanguageID int32
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, createSubmission,
		arg.ID,
		arg.Src,
		arg.Time,
		arg.ProblemID,
		arg.UserID,
		arg.LanguageID,
	)
	return err
}
