// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: test_cases.sql

package database

import (
	"context"
	"strings"
)

const batchTestCases = `-- name: BatchTestCases :many
SELECT test_case.id, test_case.created_at, test_case.updated_at, test_case.input, test_case.output, test_case.problem_id
FROM test_case
WHERE problem_id IN (/*SLICE:problem_ids*/?)
`

func (q *Queries) BatchTestCases(ctx context.Context, problemIds []string) ([]TestCase, error) {
	query := batchTestCases
	var queryParams []interface{}
	if len(problemIds) > 0 {
		for _, v := range problemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:problem_ids*/?", strings.Repeat(",?", len(problemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:problem_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestCase
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Input,
			&i.Output,
			&i.ProblemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestCases = `-- name: GetTestCases :many
SELECT problem.time_limit, problem.memory_limit, test_case.id, test_case.input, test_case.output
FROM problem
JOIN test_case 
ON problem.id = test_case.problem_id
WHERE problem_id = ?
`

type GetTestCasesRow struct {
	TimeLimit   float64
	MemoryLimit int32
	ID          string
	Input       string
	Output      string
}

func (q *Queries) GetTestCases(ctx context.Context, problemID string) ([]GetTestCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTestCases, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTestCasesRow
	for rows.Next() {
		var i GetTestCasesRow
		if err := rows.Scan(
			&i.TimeLimit,
			&i.MemoryLimit,
			&i.ID,
			&i.Input,
			&i.Output,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTestCase = `-- name: InsertTestCase :exec
INSERT INTO test_case
(id, problem_id, input, output)
VALUES (?, ?, ?, ?)
`

type InsertTestCaseParams struct {
	ID        string
	ProblemID string
	Input     string
	Output    string
}

func (q *Queries) InsertTestCase(ctx context.Context, arg InsertTestCaseParams) error {
	_, err := q.db.ExecContext(ctx, insertTestCase,
		arg.ID,
		arg.ProblemID,
		arg.Input,
		arg.Output,
	)
	return err
}

const selectTestCases = `-- name: SelectTestCases :many
SELECT id, created_at, updated_at, input, output, problem_id
FROM test_case
WHERE problem_id = ?
`

func (q *Queries) SelectTestCases(ctx context.Context, problemID string) ([]TestCase, error) {
	rows, err := q.db.QueryContext(ctx, selectTestCases, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestCase
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Input,
			&i.Output,
			&i.ProblemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
