x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

#healthcheck:
#  test: ["CMD", "curl", "-f", "http://localhost:2358/workers?X-Auth-Token=${AUTH_TOKEN}"]
#  interval: 1m30s
#  timeout: 10s
#  retries: 3
#  start_period: 40s
#  start_interval: 5s

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always
  
  #app:
  #  build: .
  #  depends_on:
  #    server:
  #      condition: service_healthy
  #      restart: true
  #  ports:
  #    - "42069:42069"
  #  env_file:
  #    - ./.env 

volumes:
  data:
