// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"
)

type Example struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Input     string
	Output    string
	ProblemID string
}

type Jwt struct {
	RefreshToken string
	CreatedAt    time.Time
}

type Language struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	DisplayName string
}

type LanguageQuiz struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LanguageID int32
	QuizID     string
}

type Participation struct {
	ID        string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ExpiresAt time.Time
	UserID    string
	QuizID    string
}

type Problem struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description string
	Title       string
	MemoryLimit int32
	TimeLimit   float64
	QuizID      string
}

type Quiz struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
	Duration    int32
	MinWage     int32
	MaxWage     int32
	UserID      string
}

type Submission struct {
	ID                string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	Src               string
	AcceptedTestCases uint32
	ProblemID         string
	ParticipationID   string
	LanguageID        int32
}

type TestCase struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Input     string
	Output    string
	ProblemID string
}

type TestCaseResult struct {
	ID           sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Status       sql.NullString
	Time         sql.NullString
	Memory       sql.NullInt32
	TestCaseID   string
	SubmissionID string
}

type User struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Email       string
	Password    string
	Role        string
	Description sql.NullString
}
