-- +goose Up
CREATE TABLE language (
  id INTEGER PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) UNIQUE NOT NULL
);

-- +goose Down
DROP TABLE language;
