-- +goose Up
CREATE TABLE user (
  id CHAR(36) PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  nick VARCHAR(32) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL DEFAULT "",
  description VARCHAR(500) NOT NULL DEFAULT "",
  image_url VARCHAR(2083) NOT NULL DEFAULT "",
  number VARCHAR(32) NOT NULL DEFAULT ""
);

-- +goose Down
DROP TABLE user;
