-- +goose Up
CREATE TABLE quiz (
  id CHAR(36) PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  duration INT NOT NULL
);

-- +goose Down
DROP TABLE quiz;
