-- +goose Up
CREATE TABLE quiz (
  id CHAR(36) PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(8191) NOT NULL,
  duration INT NOT NULL,
  min_wage INT NOT NULL,
  max_wage INT NOT NULL,
  user_id CHAR(36) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE quiz;
