-- +goose Up
CREATE TABLE offer (
  id CHAR(36) PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  about VARCHAR(5000) NOT NULL,
  requirements VARCHAR(5000) NOT NULL,
  benefits VARCHAR(5000) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  min_wage INT NOT NULL,
  max_wage INT NOT NULL,
  company_id CHAR(36) NOT NULL,
  FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE offer;
