-- +goose Up
CREATE TABLE quiz (
  id CHAR(36) PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  duration INT NOT NULL,
  offer_id CHAR(36) NOT NULL,
  FOREIGN KEY (offer_id) REFERENCES offer(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE quiz;
