-- +goose Up
CREATE TABLE link(
  id CHAR(36) PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  url VARCHAR(256) NOT NULL,
  name VARCHAR(256) NOT NULL,
  user_id CHAR(36) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(id)
);
-- +goose Down
DROP TABLE link;
